import os

PREPROCESS_INPUT_DIR = "/input/"
PREPROCESS_OUTPUT_DIR = "/scratch/"

TRAINING_INPUT_DIR = "/scratch/"
TRAINING_OUTPUT_DIR = "/output/"


PREPROCESS_INPUT_DIR_SAGEMAKER = os.getenv('SM_CHANNEL_DATASET')
PREPROCESS_OUTPUT_DIR_SAGEMAKER = '/preprocessed/'

TRAINING_INPUT_DIR_SAGEMAKER = os.getenv('SM_CHANNEL_PREPROCESSED')
TRAINING_OUTPUT_DIR_SAGEMAKER = "/artifact/"
